// search index for WYSIWYG Web Builder
var database_length = 0;

function SearchPage(url, title, keywords, description)
{
   this.url = url;
   this.title = title;
   this.keywords = keywords;
   this.description = description;
   return this;
}

function SearchDatabase()
{
   database_length = 0;
   this[database_length++] = new SearchPage("index.html", "JAB Jaya Abadi Bersama - Distributor AC", "Hubungi Kami  Pertokoan Sulung Mas 89 Blok D-21 Kec Krembangan,  Surabaya, Jawa Timur 60175  Call 0859 0001 3071  TERPERCAYA  Berdiri sejak tahun 1991, JAB merupakan pionir dalam industri penyediaan komponen otomotif di Indonesia Berawal sebagai pelopor manufaktur dan penjualan nepel, joint, dan fitting berbahan aluminium, kuningan, tembaga, serta besi, JAB kini telah berkembang menjadi pemimpin pasar yang dipercaya dalam solusi sistem pendingin kendaraan  Butuh informasi lebih lanjut ? JAYA ABADI BERSAMA  Solusi Lengkap Sparepart AC Anda  BERKUALITAS  Company Profile PENGALAMAN Melayani lebih dari 30 tahun KOMPETITIF Harga terbaik untuk anda LENGKAP Distributor sparepart AC terlengkap AHLI Dukungan penuh tim teknisi tersertifikasi Testimoni Produk Sutrisno GAPA AC Medan Tulis bebas bla bla bla bla Suku Cadang AC Kualitas Terbaik, Harga Bersaing  Mitra Terpercaya untuk Kebutuhan Sparepart AC Anda  Toni Lee 88 Auto AC Parts Jakarta Tulis bebas bla bla bla bla Ali Ridho Atlantis AC Semarang BLA BLA BLA BLA BLA Copyright © 2025 JAB Surabaya  Kursus Spesialis AC Mobil Siap kerja dan siap buka usaha ! Kami menyediakan semua kebutuhan sparepart AC mobil anda Apakah anda sedang mencari kursus otomotif dengan biaya terjangkau namun kualitas premium?  JAB Surabaya hadir memberikan solusi pelatihan terbaik untuk Anda  Kami membuka program pelatihan AC Mobil Intensif dengan sistem yang unik   Sedikit Teori, Praktek Sepuasnya!   ", "");
   this[database_length++] = new SearchPage("kursus.html", "JAB Jaya Abadi Bersama - Distributor AC", "Hubungi Kami  Pertokoan Sulung Mas 89 Blok D-21 Krembangan Sel.,  Kec Krembangan,  Surabaya, Jawa Timur 60175  Call 0859 0001 3071  Butuh informasi lebih lanjut ? Kursus Spesialis AC Mobil Siap kerja dan siap buka usaha ! Highlight Program  👨‍🏫 Instruktur  Bpk Wijaya   Praktisi Berpengalaman  30 Tahun   📍 Lokasi  Workshop JAB Surabaya 🎓 Output  Peserta Bersertifikat & Kompeten  Keunggulan Mutlak Kami   Metode Kilat & Tepat   Pembelajaran teori hanya 4 JAM  Kami langsung membedah inti masalah AC mobil tanpa bertele-tele  Magang Sepuasnya   Setelah teori, anda wajib terjun langsung  Kami menyediakan fasilitas magang sepuasnya di JAB Surabaya Anda tidak akan dilepas sampai anda merasa percaya diri dan mampu menangani kasus nyata  Harga Bersahabat   Biaya kursus yang ramah di kantong dengan fasilitas bintang lima  Siapa yang Cocok Mengikuti Kursus Ini?  Pemilik bengkel yang ingin menambah layanan AC  Lulusan SMK/Baru lulus yang ingin cepat dapat kerja  Siapapun yang ingin memiliki keahlian teknik AC seumur hidup  Tunggu apa lagi? daftar sekarang juga! hubungi nomor di bawah ini   Copyright © 2025 JAB Surabaya   ", "");
   this[database_length++] = new SearchPage("compro.html", "JAB Jaya Abadi Bersama - Company Profile", "Hubungi Kami  Pertokoan Sulung Mas 89 Blok D-21 Krembangan Sel.,  Kec Krembangan,  Surabaya, Jawa Timur 60175  Call 0859 0001 3071  Butuh informasi lebih lanjut ? Company Profile Berdiri sejak tahun 1991, JAB merupakan pionir dalam industri penyediaan komponen otomotif di Indonesia Berawal sebagai pelopor manufaktur dan penjualan nepel, joint, dan fitting berbahan aluminium, kuningan, tembaga, serta besi, JAB kini telah berkembang menjadi pemimpin pasar yang dipercaya dalam solusi sistem pendingin kendaraan  Dengan pengalaman lebih dari tiga dekade, kami terus konsisten mengedepankan kualitas dan inovasi produk untuk memenuhi kebutuhan industri otomotif yang dinamis   Perjalanan & Pencapaian  1991  Pendirian perusahaan sebagai pelopor produk nepel, joint, dan fitting di Indonesia  1998  Ekspansi bisnis ke segmen suku cadang  spare parts  AC Mobil  2003  Memulai langkah strategis sebagai importir langsung suku cadang AC dari Tiongkok untuk memastikan ketersediaan produk berkualitas dengan harga kompetitif  2016  Peluncuran beberapa proprietary brands  merek mandiri , yang meliputi  CPARTS, SUPERKING, UTS, BOSTON, dan NICHIRO TEFURON  Visi    Menjadi institusi terbaik dalam sejarah industri AC Mobil di Indonesia serta menjadi berkat bagi sesama  Misi  Menghidupkan semangat para pelaku usaha dagang dan bengkel AC Mobil di seluruh Indonesia Mendorong pertumbuhan pengusaha baru dan talenta muda agar berhasil dalam ekosistem perdagangan serta perbengkelan AC Mobil Terus melakukan inovasi produk dan pengembangan pasar melalui kerja sama strategis yang saling menguntungkan  Komitmen Kami JAB memprioritaskan kekuatan dagang melalui kolaborasi yang baik dengan seluruh pemangku kepentingan Kami berkomitmen untuk terus menghadirkan produk berkualitas tinggi yang diakui baik di tingkat nasional maupun mancanegara   Salam hangat,  W I J A Y A Manajemen JAB  Portofolio Produk & Kemitraan  Hingga saat ini, JAB memiliki koleksi lebih dari 1150 jenis Neple dan spare parts AC yang dirancang khusus untuk berbagai jenis kendaraan, mulai dari AC Mobil, Bus, Truk, hingga Alat Berat Hal ini menjadikan JAB mitra strategis utama dalam pengadaan komponen teknis AC yang presisi  Selain merek mandiri, JAB juga dipercaya sebagai distributor resmi dan pemegang merek ternama dunia, antara lain  NICHIRIN, VALEO, HBS dan FUJIKOKI  Copyright © 2025 JAB Surabaya   ", "");
   this[database_length++] = new SearchPage("produk.html", "JAB Jaya Abadi Bersama - Produk", "Hubungi Kami  Pertokoan Sulung Mas 89 Blok D-21 Krembangan Sel.,  Kec Krembangan,  Surabaya, Jawa Timur 60175  Call 0859 0001 3071  Butuh informasi lebih lanjut ? Kategori KOMPRESOR KONDENSOR OLI PANEL KONTROL EVAPORATOR MOTOR BLOWER FILTER CHEMICAL SEAL SELANG MAGNET CLUTCH CHEMICAL Copyright © 2025 JAB Surabaya   ", "");
   this[database_length++] = new SearchPage("produk-kompresor.html", "JAB Jaya Abadi Bersama - Kompresor", "Hubungi Kami  Pertokoan Sulung Mas 89 Blok D-21 Krembangan Sel.,  Kec Krembangan,  Surabaya, Jawa Timur 60175  Call 0859 0001 3071  Butuh informasi lebih lanjut ? Kompresor NISSAN  X-TRAIL T31 DAI SIGRA /  TOY CALYA NISSAN  X-TRAIL T32 MERCEDES BENZ  ACTROS 7SBU 16C MAZDA  CX - 7 DAIHATSU  XENIA DAIHATSU  NEW XENIA 1.0 DAIHATSU  NEW GRAN MAX 10 P 15 10 P 13 10 P 30 B 10 PA 15 C 10 PA 17 10 PA 20 C 505 SD 12V 507 SD 12V 508 SD 12V 508 SD 24V AB MERCY 9PK 24V AB SUNNY CHEVROLET  SPIN BENSIN 6PK DATSUN  GO FORD  RANGER NEW HITACHI  R134A HONDA  BRIO 1.2 HONDA  CIVIC 88 HONDA  CR-V 2.0 HONDA  FREED HONDA  GENIO HONDA  JAZZ OLD HONDA  MOBILIO HONDA  STREAM MODEL ND KARIMUN  ESTILLO KIA  PICANTO OLD KIA  PICANTO NEW KIA RIO 2012 /  AVEGA 2013 MITSUBISHI  XPANDER MITSUBISHI  NEW TRITON MITSUBISHI  OUTLANDER MITSUBISHI  PAJERO 2018 MITSUBISHI  L-200 ND KECIL /   FORZA NISSAN  GRAND LIVINA 1.8 NISSAN  LIVINA NISSAN  XTRAIL 2.0 SUZUKI  AERIO SUZUKI  APV ARENA SUZUKI  SWIFT 2013 TOY AGYA /  DAI AYLA TOY ALL NEW  AVANZA TOYOTA  AVANZA TOY ALL NEW  YARIZ TOY GRAND  AVANZA TOY INNOVA  BENSIN TOY INNOVA  DIESEL TOY INNOVA  REBORN 7PK SUZUKI  ERTIGA TOYOTA INNOVA  BENSIN TOYOTA INNOVA  DIESEL TOYOTA INNOVA  REBORN TOYOTA INNOVA  ZENIX TOYOTA GRAND  AVANZA TOYOTA  ALL NEW YARIS TOYOTA ALL  NEW AVANZA WULING  CONFERO WULING  FORMO TOYOTA  OLD AVANZA Copyright © 2025 JAB Surabaya   ", "");
   return this;
}
